# Generated by Django 4.1.5 on 2023-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('Bw', 'Bottom Wear'), ('T-shirt', 'tShirt'), ('saree', 'saree'), ('Ev', 'eletronic Vechile'), ('Pv', 'Petrol Vechile')], max_length=3000),
        ),
    ]
