# Generated by Django 4.1.5 on 2023-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delevered', 'Delevered'), ('Cancel', 'Cancel')], default='Accepted', max_length=50),
        ),
    ]
